### ISSUE TITLE
Public Key Hash Check failing

### ISSUE THREAD

**Issue by BrandoCommando** [etsy/applepay-php#4]
Aside from bypassing the actual hash check, no matter what I do, I cannot get the _applepay_verify_pubkey_hash to pass. If I bypass this function (i.e. comment out "return APPLEPAY_ERROR_FAILED_TO_VERIFY_PUBKEY_HASH") then everything decrypts and works great. Any advice on what went wrong?

**Comment by adamelso** [comment]
I'm having the same issue as well - I recreated all the certificates just in case, yet it still fails at this step.

**Comment by adsr** [comment]
I suggest peeking at the values of `cert_digest` and `pubkey_hash` in `_applepay_verify_pubkey_hash` to see what's up. I can help debug if someone supplies test inputs to reproduce.

**Comment by adamelso** [comment]
Thanks @adsr , I have a demo site that you can test on. Let me know if you need any more info.

**Comment by peteward** [comment]
Hi @adsr, I'm working with @adamelso and we're not making much progress after a couple of weeks trying to decrypt with your module. We really appreciate your work and if there's any chance you could take a look and help us out - we'd be very grateful.

Thanks!

**Comment by adsr** [comment]
I am getting a 404 on https://github.com/adamelso/touch-merchant/invitations Can you resend the invitation?

**Comment by adamelso** [comment]
For anyone stuck on this, I've discovered that using just a PEM file that contained only the certificate when requesting a merchant session would create in invalid hash because both the certificate and the public key are actually required in the same file - which is what this extension is expecting to use when verifying/decrypting.

Apple doesn't tell you how it created this file in their (Emporium example)[https://developer.apple.com/library/content/samplecode/EmporiumWeb/Listings/Emporium_app_js.html#//apple_ref/doc/uid/TP40017557-Emporium_app_js-DontLinkElementID_3] and even suggests using the same file for both the certificate and SSL key options of the request, but this may not work, so I had to convert the .p12 file to PEM format and use that as the SSL key option.

Example with Guzzle.

```php
$url = '...'; // URL is returned  From Apple Pay JS event for session.onvalidatemerchant
$client = new \GuzzleHttp\Client();
$res = $client->request('POST', $url, [
            RequestOptions::CERT    => 'pub.pem', // This file is created using the README instructions in this repo
            RequestOptions::SSL_KEY => 'priv.pem', // PEM format of priv.p12 key.

            RequestOptions::JSON => [
                'merchantIdentifier' => 'merchant.com.foo',
                'domainName'         => 'www.mystore.com',
                'displayName'        => 'My Store',
            ],
]);
```


The contents of that `RequestOptions::CERT` file should be that of `pub.pem`, which looks like this:

GOOD: Public Key + Certificate

```
-----BEGIN PUBLIC KEY-----
...
(some  base64)
...
-----END PUBLIC KEY-----
-----BEGIN CERTIFICATE-----
...
(some more base64)
...
-----END CERTIFICATE-----

```


BAD: Certificate, but no public key

```
-----BEGIN CERTIFICATE-----
...
(some more base64)
...
-----END CERTIFICATE-----
```
