### ISSUE TITLE
Decrypt for RSA option.

### ISSUE THREAD

**Issue by adamelso** [etsy/applepay-php#5]
The extension at the moment only considers decryption for ECC, which was for the longest time the only encryption option available.

Now when following Apple's instructions on creating Apple Pay Merchant ID certificates, RSA is used as the encryption option.

Though oddly enough, `EC_v1` is returned as the value of `token.paymentData.version` when a payment is authorised for a merchant with this setup.

This means when attempting to decrypt, the error `APPLEPAY_ERROR_COULD_NOT_INIT_SECRET_CTX` is raised.

**Comment by adamelso** [comment]
Also, unfortunately specificing EC for new CSRs is not possible because Apple only accepts RSA for new Merchants:

![screen shot 2017-07-24 at 11 46 54](https://user-images.githubusercontent.com/5972864/28520066-fe9871f6-7065-11e7-90c0-4feb16607044.png)

**Comment by peteward** [comment]
Hi @adsr,

Unfortunately we've hit a roadblock with this - since we can't generate an EC cert that Apple will accept and the module doesn't support RSA :(

I'm very grateful for you and your team's work on this already, but is there any chance you would consider adding RSA support any time soon? I'm not sure of the effort involved. From the looks of the SSL library it doesn't seem enormous although difficult if ApplePay isn't reporting the type of certificate correctly...

We might be able to loosely 'sponsor' the work if that would help. Feel free to get in touch, my email is in my profile.

Thanks!

**Comment by adsr** [comment]
I also don't think it will be that much work. Once we have an example RSA cryptogram and cert I will add support.

**Comment by peteward** [comment]
Is there anything we can do to help? Can we share ours as the example?

**Comment by adsr** [comment]
@peteward I will follow-up via email.

**Comment by adsr** [comment]
See #6
